galaxy_info:
  author: Ed Stewart
  description: |
    Imports (or reimports) Job Templates from /files/bootstrap-awx-job-templates*.yml files into AWX automatically.  The role also optionally initiates (and waits for) the OHC Undercloud and Overcloud build.  Finally, the role enables all scheduled jobs.
  company: Atos

  license: |
    Copyright © 2019 Atos. All rights reserved.
    No part of this document can be copied, reproduced, translated, modified and/or adapted or
    stored on electronic storage without the written agreement of Atos.
    Please refer to the agreement under which you have been given access to this source code for
    the exact terms and conditions. 

  min_ansible_version: 2.4

  galaxy_tags:
    - cloud
    - gcp
    - openstack

dependencies: []
